name: Build process

on:  
  push:
    branches: 
      - main
  
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
    name: github-pages
    url: ${{steps.deployment.outputs.page_url}}
    name : Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version : [16.x,18.x]
    defaults:
      run:
        working-directory: vitehosting
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: check current dir
        run: pwd
      - name: list of files
        run: ls
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install npm packages        
        run: npm install
      - name: Build App
        
        run: npm run build
      - name: list of files
        run: ls
      - name: Upload prod files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./vitehosting/dist
      - name: check current dir
        run: pwd
      - name: list of files
        run: ls
               
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:          
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      